### PR TITLE
Review and choose Typescript publish approach.

### PR DESCRIPTION
**Pull request by vagabondrev**
Per previous PR discussion w/Clement, we have two options for publication of TS definitions with the package.

Per [Typescript docs](https://www.typescriptlang.org/docs/handbook/declaration-files/publishing.html) we have two options:

1. bundling with your npm package
2. publishing to the [@types organization](https://www.npmjs.com/~types) on npm.

I've modified the tsconfig.json file with comments and configurations for each option. We just need to agree on an approach and choose one. There are pros/cons to each approach; I'm presently leaning toward option 2, but would appreciate input.

I also did a file compare on the output for option one, (the ./dist folder), and there appears to be some .json schema definition files from the ./src/schema folder that are not getting moved to the ./dist output folder. Not sure how these are used by the framework, or if they need to be included. If so we'll need to make sure they get copied as well.

Let me know your thoughts.

Scott -

### CODE REVIEW

**Comment by vagabondrev** [comment]
Quick update: I copied the definitions from the @types/epcis2.js folder of the new build output to the node_modules folder of my project, and they're working perfectly along with the existing NPM download of the framework.

This reinforces my opinion we should go with option 2; it will add Typescript support with minimal disruption to the existing distribution approach, (i.e. any developers currently using the framework for javascript only will not be affected).

**Comment by clementh59** [comment]
Hi Scott, thanks again for the PR. 

Here is what I found in the docs: 

> If your types are generated by your source code, publish the types with your source code. Both TypeScript and JavaScript projects can generate types via [declaration](https://www.typescriptlang.org/tsconfig#declaration).

Wouldn't it make more sense for us to publish the types within the same package?

**Comment by clementh59** [comment]
It makes sense to go for option 2 in this case indeed. Thanks a lot for the clear explanation. I guess the configuration file is already ready then, right?
Should we also add some config to publish the @types to the @types npm org or is it done automatically?

**Comment by clementh59** [comment]
Oh, I just we only need to do a pull request to add them. I'll look into it.

**Comment by vagabondrev** [comment]
Yes, the config file is ready to go. Looks like we're almost there. Let me know if you need any more help. Thanks!

**Comment by clementh59** [comment]
Great, I'll merge the PR once the types are published then :)
I created a PR there: https://github.com/DefinitelyTyped/DefinitelyTyped/pull/63827
Thanks a lot!

**Comment by jakebailey** [comment]
> Not sure why MSFT took these two clarifying sentences out of the docs, but the reasoning is that if you have generated your types as part of your module, you should bundle with the package.

Copying the full section  of the [publishing page](https://www.typescriptlang.org/docs/handbook/declaration-files/publishing.html):

> If your types are generated by your source code, publish the types with your source code. Both TypeScript and JavaScript projects can generate types via declaration.
> 
> Otherwise, we recommend submitting the types to DefinitelyTyped, which will publish them to the @types organization on npm.

I'm not sure what is missing from that phrasing.

Just to state it, it's not abnormal to publish hand-written d.ts files with packages either, even if the packages aren't in JS; if that works for your deployment, it can be better for users from the POV that they don't need to go through a second step after realizing they're missing types. But, you do have to publish a new version of the package to get newer types, which some people don't like. (Obviously, the best thing is to just [use TS](https://www.typescriptlang.org/docs/handbook/migrating-from-javascript.html), but, that's a different hurdle.)

**Review by clementh59 — APPROVED** [review]

**Comment by clementh59** [comment]
Thanks both!
The types are now published there: https://github.com/DefinitelyTyped/DefinitelyTyped/tree/master/types/epcis2.js

**Pull request merged**
